services:
  web:
    image: ghcr.io/pham-0/archdev-demo:latest
    ports:
      - "8090:80"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 60
    restart: unless-stopped
