version: "3"
services:
  web:
    build: ./app
    container_name: archdev-demo-web-1
    restart: unless-stopped
    ports:
      - "8080:80"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /home/pham/.cloudflared:/etc/cloudflared
    depends_on:
      - web
