name: Build & Push Docker (bare)
on:
  workflow_dispatch: {}
  push: { branches: [ "main" ] }
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: archdev
    steps:
      - name: Debug env & docker
        run: |
          set -euxo pipefail
          echo "Actor=$GITHUB_ACTOR"
          echo "Repo=$GITHUB_REPOSITORY"
          docker --version
          docker info || true

      - name: Clone source via git (no actions/checkout)
        run: |
          set -euo pipefail
          rm -rf repo && mkdir repo
          git -C repo init
          git -C repo remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          if [ -n "${GITHUB_SHA:-}" ]; then
            git -C repo fetch origin "$GITHUB_SHA" --depth=1
          else
            git -C repo fetch origin "${GITHUB_REF_NAME:-main}" --depth=1
          fi
          git -C repo checkout FETCH_HEAD
          git -C repo log --oneline -n 1

      - name: Login GHCR (non-TTY via stdin)
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          test -n "$CR_PAT" || (echo "GITHUB_TOKEN empty" && exit 1)
          echo "$CR_PAT" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

      - name: Build & Push
        run: |
          set -euo pipefail
          cd repo
          IMAGE="ghcr.io/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')"
          docker build -t "$IMAGE:latest" .
          docker tag "$IMAGE:latest" "$IMAGE:${GITHUB_SHA}"
          docker push "$IMAGE:${GITHUB_SHA}"
          docker push "$IMAGE:latest"
